api:
  name: "Simple_Post_App_API"
  security:
    token:
      secret: "${JWT_SECRET}"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '050306'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true